Repository PowerLevel9000/School-library, pull requests merged in 2023-04, with the labels that each got.

#2 Setup poject initialize
  README.md
  hello.rb
  person.rb
  student.rb
  teacher.rb
Labels: documentation, enhancement

#3 OOP school library: decorate a class
  README.md
  capitalize_dacorator.rb
  decorator.rb
  nameable.rb
  person.rb
  student.rb
  trimmer_decorator.rb
Labels: enhancement

#4 Associations
  book.rb
  capitalize_dacorator.rb
  classroom.rb
  console.rb
  decorator.rb
  nameable.rb
  person.rb
  rental.rb
  student.rb
  teacher.rb
  trimmer_decorator.rb
Labels: enhancement, help wanted

#5 OOP school library: add basic UI
  app.rb
  console.rb
  main.rb
Labels: enhancement, help wanted

#7 Milestone 2. with Pairprogramming in School-library project on preserve-data Branch
  README.md
  app.rb
  book.rb
  data-controler/data/books.json
  data-controler/data/classroom.json
  data-controler/data/person.json
  data-controler/data/rentals.json
  data-controler/data_presever.rb
  main.rb
  person.rb
  rental.rb
  ui_creater.rb
Labels: enhancement

#8 OOP school library: unit tests
  README.md
  classroom.rb
  decorator.rb
  spec/book_spec.rb
  spec/capitalize_decorator.spec.rb
  spec/classroom_spec.rb
  spec/decorator_spec.rb
  spec/nameable_spec.rb
  spec/person_spec.rb
  spec/rental_spec.rb
  spec/spec_helper.rb
  spec/student_spec.rb
  spec/teacher_spec.rb
  spec/trimmer_decorator_spec.rb
  student.rb
Labels: enhancement
